spring:
  application:
    name: AnyQuizAI
  profiles:
    active: '@spring.profiles.active@'
  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false
  ai:
    openai.api-key: ${OPENAI_API_KEY}