spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/anyquizaidb
    username: myuser
    password: secret
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  elasticsearch:
    password: "secret"
    uris: http://localhost:9200
    connection-timeout: 300s
  docker:
    compose:
      enabled: false
