spring:
  application:
    name: AnyQuizAI
  profiles:
    active: '@spring.profiles.active@'
  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false
  ai:
    openai.api-key: ${OPENAI_API_KEY}
springdoc:
  api-docs:
    path: /api-docs
application:
  quiz-photos-path: "/var/quiz_photos"
  quiz-photo-height: 1024
  quiz-photo-width: 1024
