spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/anyquizaidb
    username: myuser
    password: secret
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      enabled: false

