INSERT INTO category (name) VALUES
                                ('STEM (Science, Technology, Engineering, Mathematics)'),
                                ('Humanities'),
                                ('Social Sciences'),
                                ('Arts'),
                                ('Language and Literature'),
                                ('General Knowledge'),
                                ('History and Culture'),
                                ('Geography'),
                                ('Life Sciences'),
                                ('Physical Sciences'),
                                ('Computer Science and IT'),
                                ('Health and Medicine'),
                                ('Business and Economics'),
                                ('Environmental Studies'),
                                ('Philosophy and Ethics'),
                                ('Music and Performing Arts'),
                                ('Sports and Recreation'),
                                ('Other');